##{PropertiesConnector} savedBy=jason, saveDate=Wed Sep 30 07:23:43 CDT 2026
ldapAdminDN=cn=admin,dc=example,dc=com
ldapAdminPwd=
ldapSearchBase_people=ou=People, dc=example,dc=com
ldapSearchBase_group=ou=Groups, dc=example,dc=com
ldapUrl=ldap://localhost:389
bearerToken=
